on:
  push:
    branch:
      - main

jobs:
  run-ts-analysis:
    strategy:
      matrix:
        config:
          - { os: ubuntu-latest, r: "release", python: "3.9" }
    runs-on: ${{ matrix.config.os }}

    env:
      RENV_PATHS_ROOT: ~/.local/share/renv
      POETRY_VERSION: 1.1.11
      POETRY_URL: https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      SLACK_TEST_CH_ID: ${{ secrets.SLACK_TEST_CH_ID }}

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@master
        with:
          r-version: ${{ matrix.config.r }}

      - name: Cache R packages
        uses: actions/cache@v2
        with:
          path: ${{ env.RENV_PATHS_ROOT }}
          key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
          restore-keys: |
            ${{ runner.os }}-renv

      - name: Cache Poetry cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/pypoetry
          key: poetry-cache-${{ runner.os }}-${{ matrix.config.python }}-${{ env.POETRY_VERSION }}

      - name: Cache Python packages
        uses: actions/cache@v2
        with:
          path: ~/.local
          key: poetry-${{ runner.os }}-${{ matrix.config.python }}-${{ hashFiles('**/poetry.lock') }}-${{ hashFiles('.github/workflows/*.yml') }}

      # ubuntuで`curl`を入れるためには必須
      - name: Install libcurl
        run: sudo apt install libcurl4-openssl-dev

      - name: Restore R packages
        shell: Rscript {0}
        run: |
          if (!require("renv", quietly=TRUE)) install.packages("renv")
          renv::restore()

      - name: Run analysis code
        run: Rscript -e "source('R/run_ts_analysis.r')"

      - name: Set up Python ${{ matrix.config.python }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.config.python }}

      - name: Install poetry
        run: |
          curl -sSL ${{ env.POETRY_URL }} | python - --version ${{ env.POETRY_VERSION }}
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install Python packages
        run: poetry install

      - name: Send image to slack
        run: poetry run python slack/file_sender.py Output/result1.png

      - name: Remove output image
        run: rm -f Output/result1.png
